# This is a basic workflow that is manually triggered

name: CI/CD example

on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Validate translations
      run: sleep 5 && echo "Validation complete"
